from datetime import datetime, timezone

import pytest

from src.data.candle import Candle


@pytest.fixture
def backtest_candles() -> list[Candle]:
    return [
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 0, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.00,
            high=1.01,
            low=0.99,
            close=1.00,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 1, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.00,
            high=1.06,
            low=0.99,
            close=1.05,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 2, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.05,
            high=1.06,
            low=1.04,
            close=1.04,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 3, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.04,
            high=1.06,
            low=1.04,
            close=1.05,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 4, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.05,
            high=1.07,
            low=1.04,
            close=1.06,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 5, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.06,
            high=1.06,
            low=1.04,
            close=1.05,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 6, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.05,
            high=1.06,
            low=1.04,
            close=1.04,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 7, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.04,
            high=1.06,
            low=1.04,
            close=1.05,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 8, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.05,
            high=1.06,
            low=1.03,
            close=1.04,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 9, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.04,
            high=1.05,
            low=1.03,
            close=1.04,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 10, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.04,
            high=1.05,
            low=1.03,
            close=1.04,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 11, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.04,
            high=1.05,
            low=1.03,
            close=1.04,
            volume=None,
        ),
        Candle(
            symbol="EURUSD",
            timestamp=datetime(2026, 8, 17, 10, 12, tzinfo=timezone.utc),
            timeframe="1m",
            open=1.04,
            high=1.05,
            low=1.03,
            close=1.04,
            volume=None,
        ),
    ]